version: "3.1"
services:
  auth2:
    image: kbase/kb_auth2:alpine
    ports:
      - "8080:8080"
    environment:
      - KB_DEPLOYMENT_CONFIG=/kb/deployment/conf/deployment.cfg
    command:
      - "-wait"
      - "tcp://ci-mongo:27017"
      - "-wait"
      - "tcp://mongoinit:8080"
      - "-timeout"
      - "120s"
      - "-template"
      - "/kb/deployment/conf/.templates/deployment.cfg.templ:/kb/deployment/conf/deployment.cfg"
      - "/kb/deployment/bin/start_auth2.sh"
    depends_on: ["ci-mongo", "mongoinit"]

  mongoinit:
    image: kbase/db_initialize:latest
    volumes:
      - ./auth2.mongodump:/mnt/auth2.mongodump
    entrypoint:
      - "/kb/deployment/bin/dockerize.sh"
      - "-wait"
      - "tcp://ci-mongo:27017"
      - "-timeout"
      - "120s"
      - "mongorestore"
      - "--host"
      - "ci-mongo"
      - "/mnt/auth2.mongodump"
    depends_on: [ "ci-mongo" ]
  
  ci-mongo:
    image: mongo:2
    ports:
      - "27017:27017"

